name: Docker Image CI

on:
  push:
    branches:
      - main
      - '**'  # Triggers on all branches
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx (for cross-platform builds or caching support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract branch or tag name
        id: extract_ref
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "ref_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "ref_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "ref_name=unknown" >> $GITHUB_ENV
          fi
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm64/v8
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/logalanche
            org.opencontainers.image.description="Log generator for demos and testing"
            org.opencontainers.image.licenses=MIT
          tags: |
            ghcr.io/${{ github.repository_owner }}/logalanche:latest
            ghcr.io/${{ github.repository_owner }}/logalanche:${{ env.ref_name }}
  
      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
