name: Docker Image CI

on:
  push:
    branches:
      - main
      - '**'  # Triggers on all branches
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Docker registry
      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Set up Docker Buildx (for cross-platform builds or caching support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        id: build
        run: |
          # Determine the image tag based on whether it's a branch, tag, or main
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            IMAGE_TAG="latest"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          else
            IMAGE_TAG="${GITHUB_REF#refs/heads/}"
          fi

          # Build the Docker image
          docker build -t ghcr.io/${{ github.repository }}/logalanche:${IMAGE_TAG} .

      # Push the Docker image to GitHub Docker Registry
      - name: Push Docker image
        run: |
          # Push the built image
          docker push ghcr.io/${{ github.repository }}:${IMAGE_TAG}

      # Optionally push the 'latest' tag for the main branch
      - name: Tag 'latest' for main
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/${{ github.repository }}/logalanche:main ghcr.io/${{ github.repository }}/logalanche:latest
          docker push ghcr.io/${{ github.repository }}/logalanche:latest

